version: "2"

linters:
  enable:
    - bodyclose
    - gosec
    - govet
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - whitespace
  disable:
    - errcheck
    - ineffassign
    - unused
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    rules:
      - text: '(slog|log)\.\w+'
        linters:
          - noctx
      - path: '_test\.go'
        linters:
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
