version: 2

project_name: mocode

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    goos: linux
    goarch: amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: mocode_linux_amd64

  - id: linux-arm64
    goos: linux
    goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: mocode_linux_arm64

  - id: darwin-amd64
    goos: darwin
    goarch: amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: mocode_darwin_amd64

  - id: darwin-arm64
    goos: darwin
    goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: mocode_darwin_arm64

  - id: windows-amd64
    goos: windows
    goarch: amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: mocode_windows_amd64.exe

archives:
  - format: zip
    format_overrides:
      - goos: windows
        format: binary

checksum:
  name_template: 'mocode_checksums.txt'
  algorithm: sha256

release:
  github:
    owner: nextsko
    name: mocode-build
  draft: false
  prerelease: false
  name_template: '{{.Tag}}'
  body_template: |
    ## What's Changed

    {{range .Commits}}
    - {{.Message}}
    {{end}}

    **Full Changelog**: https://github.com/nextsko/mocode-build/compare/{{.PreviousTag}}...{{.Tag}}
