# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

project_name: Mocode

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion bash >./completions/Mocode.bash'
    - sh -c 'go run . completion zsh >./completions/Mocode.zsh'
    - sh -c 'go run . completion fish >./completions/Mocode.fish'
    - sh -c 'go run . man | gzip -c >./manpages/Mocode.1.gz'

builds:
  - id: Mocode
    main: .
    binary: Mocode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X github.com/package-register/mocode/internal/version.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm}}v{{ . }}{{ end }}
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: packages
    package_name: Mocode
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    contents:
      - src: ./completions/Mocode.bash
        dst: /etc/bash_completion.d/Mocode
      - src: ./completions/Mocode.fish
        dst: /usr/share/fish/vendor_completions.d/Mocode.fish
      - src: ./completions/Mocode.zsh
        dst: /usr/share/zsh/site-functions/_Mocode
      - src: ./manpages/Mocode.1.gz
        dst: /usr/share/man/man1/Mocode.1.gz

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

changelog:
  sort: asc
  filters:
    exclude:
      - "^(build|ci): "
      - "^chore: auto-update generated files$"
      - "^chore\\(legal\\): "
      - "^chore\\(deps\\): "
      - "^docs: update$"
      - "^test:"
      - "^test\\("
      - "^v\\d.*"
      - "merge conflict"
      - "Merge branch"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "go mod tidy"
  groups:
    - title: "New features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Other"
      order: 9999

release:
  prerelease: auto
